extern const GeoLayout castle_door_new_geo[];
extern u8 castle_door_new_Castle_Door_ci8[];
extern u8 castle_door_new_Castle_Door_pal_rgba16[];
extern u8 castle_door_new_Gold_ci8[];
extern u8 castle_door_new_Gold_pal_rgba16[];
extern Vtx castle_door_new_000_offset_002_mesh_layer_1_vtx_0[149];
extern Gfx castle_door_new_000_offset_002_mesh_layer_1_tri_0[];
extern Vtx castle_door_new_000_offset_002_mesh_layer_1_vtx_1[95];
extern Gfx castle_door_new_000_offset_002_mesh_layer_1_tri_1[];
extern Gfx mat_castle_door_new_Castle_Door[];
extern Gfx mat_revert_castle_door_new_Castle_Door[];
extern Gfx mat_castle_door_new_Gold[];
extern Gfx mat_revert_castle_door_new_Gold[];
extern Gfx castle_door_new_000_offset_002_mesh_layer_1[];
