extern const GeoLayout purple_switch_geo[];
extern u8 purple_switch_Purple_Button_ci8[];
extern u8 purple_switch_Purple_Button_pal_rgba16[];
extern u8 purple_switch_Gold_ci8[];
extern u8 purple_switch_Gold_pal_rgba16[];
extern Vtx purple_switch_000_displaylist_mesh_layer_5_vtx_0[8];
extern Gfx purple_switch_000_displaylist_mesh_layer_5_tri_0[];
extern Vtx purple_switch_000_displaylist_mesh_layer_1_vtx_0[22];
extern Gfx purple_switch_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_purple_switch_Purple_Button_001[];
extern Gfx mat_revert_purple_switch_Purple_Button_001[];
extern Gfx mat_purple_switch_Gold[];
extern Gfx mat_revert_purple_switch_Gold[];
extern Gfx purple_switch_000_displaylist_mesh_layer_5[];
extern Gfx purple_switch_000_displaylist_mesh_layer_1[];
