extern const GeoLayout cannon_barrel_geo[];
extern u8 cannon_barrel_Purple_Blue_Shine_ci8[];
extern u8 cannon_barrel_Purple_Blue_Shine_pal_rgba16[];
extern u8 cannon_barrel_Shine_i8[];
extern Vtx cannon_barrel_000_displaylist_mesh_layer_1_vtx_0[64];
extern Gfx cannon_barrel_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx cannon_barrel_000_displaylist_mesh_layer_1_vtx_1[190];
extern Gfx cannon_barrel_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_cannon_barrel_Purple_Blue_Shine[];
extern Gfx mat_revert_cannon_barrel_Purple_Blue_Shine[];
extern Gfx mat_cannon_barrel_Shine[];
extern Gfx mat_revert_cannon_barrel_Shine[];
extern Gfx cannon_barrel_000_displaylist_mesh_layer_1[];
