extern const GeoLayout yellow_coin_geo[];
extern u8 yellow_coin_Orange_Shine_ci8[];
extern u8 yellow_coin_Orange_Shine_pal_rgba16[];
extern u8 yellow_coin_Darker_Orange_Shine_ci8[];
extern u8 yellow_coin_Darker_Orange_Shine_pal_rgba16[];
extern Vtx yellow_coin_000_displaylist_mesh_layer_1_vtx_0[135];
extern Gfx yellow_coin_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx yellow_coin_000_displaylist_mesh_layer_1_vtx_1[136];
extern Gfx yellow_coin_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_yellow_coin_Orange_Shine[];
extern Gfx mat_revert_yellow_coin_Orange_Shine[];
extern Gfx mat_yellow_coin_Darker_Orange_Shine[];
extern Gfx mat_revert_yellow_coin_Darker_Orange_Shine[];
extern Gfx yellow_coin_000_displaylist_mesh_layer_1[];
