extern const GeoLayout red_coin_geo[];
extern u8 red_coin_Red_Shine_ci8[];
extern u8 red_coin_Red_Shine_pal_rgba16[];
extern u8 red_coin_Darker_Red_Shine_ci8[];
extern u8 red_coin_Darker_Red_Shine_pal_rgba16[];
extern Vtx red_coin_000_displaylist_mesh_layer_1_vtx_0[135];
extern Gfx red_coin_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx red_coin_000_displaylist_mesh_layer_1_vtx_1[136];
extern Gfx red_coin_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_red_coin_Red_Shine[];
extern Gfx mat_revert_red_coin_Red_Shine[];
extern Gfx mat_red_coin_Darker_Red_Shine[];
extern Gfx mat_revert_red_coin_Darker_Red_Shine[];
extern Gfx red_coin_000_displaylist_mesh_layer_1[];
